packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@biomejs/biome': ^1.9.4
  typescript: ^5.8.3
  '@tailwindcss/postcss': ^4.1.4
  postcss: ^8.5.3
  tailwindcss: ^4.1.4
  depcheck: ^1.4.7
  next-auth: ^5.0.0-beta
  pg: ^8.15.6
  kysely: ^0.28.2
  '@t3-oss/env-nextjs': ^0.13.0
  zod: ^3.24.3
  jiti: ^2.4.2
  next: ^15.3.1
  react-hook-form: ^7.56.1
  '@hookform/resolvers': ^5.0.1
catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2
    '@types/node': ^22.15.3
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
