packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  # Tooling
  '@biomejs/biome': ^1.9.4
  typescript: ^5.8.3
  '@tailwindcss/postcss': ^4.1.4
  postcss: ^8.5.3
  tailwindcss: ^4.1.4

  # Misc
  zod: ^3.24.3
catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js-pure
  - sharp
