import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import "@core/tailwind-config/shared.css";

const calSans = localFont({
    src: "./fonts/CalSans.woff2",
    variable: "--font-cal-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${calSans.variable}`}>{children}</body>
        </html>
    );
}
